FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml .

RUN npm install -g pnpm && pnpm install

COPY . .

COPY .env.production .env

RUN pnpm run build

RUN npm install serve -g

EXPOSE 3000

CMD [ "npx", "serve", "-s", "dist" ]