version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.main
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - NODE_ENV=${NODE_ENV}
        - MODE=${NODE_ENV}
    env_file:
      - stack.env

    networks:
      develop:
        ipv4_address: ${IPV4}
        aliases:
          - ${NETWORK_ALIAS_NAME}
    restart: unless-stopped

networks:
  develop:
    external: true
