/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Sarnegar API
 * Your project description
 * OpenAPI spec version: 0.1.0
 */
import { api } from "./api.instance";
export interface Drug {
  readonly id?: number;
  /** @maxLength 256 */
  en_name: string;
  /** @maxLength 256 */
  fa_name: string;
  /** @maxLength 256 */
  producer: string;
  /**
   * آپلود تصویر دارو (فقط JPG، JPEG، PNG)
   * @pattern (?:jpg|jpeg|png)$
   */
  image: string;
}

/**
 * Serializer for creating and updating DrugDosage instances
 */
export interface DrugDosageCreateUpdateRequest {
  drug: number;
  /** Structured dose information including amount and unit. */
  dose: unknown;
  /** List of reminders with time and labels. */
  reminder_times: ReminderTimeRequest[];
  type_of_usage?: TypeOfUsageEnum;
  start_date: string;
  /** @nullable */
  end_date?: string | null;
  /**
   * @minimum 1
   * @maximum 2147483647
   * @nullable
   */
  end_by_day?: number | null;
  is_daily?: boolean;
  /** Days of the week when the drug should be taken (e.g., MON, TUE). */
  usage_days?: UsageDaysEnum[];
}

/**
 * Serializer for retrieving DrugDosage instances with expanded drug information
 */
export interface DrugDosageRetrieve {
  readonly id?: number;
  drug: Drug;
  dose?: unknown;
  /** List of reminders with time and labels. */
  reminder_times: ReminderTime[];
  type_of_usage?: TypeOfUsageEnum;
  start_date: string;
  /** @nullable */
  end_date?: string | null;
  /**
   * @minimum 1
   * @maximum 2147483647
   * @nullable
   */
  end_by_day?: number | null;
  is_daily?: boolean;
  total_doses: number;
  taken_doses: number;
  /** Days of the week when the drug should be taken (e.g., MON, TUE). */
  usage_days?: UsageDaysEnum[];
  /** Indicates if the dosage is currently active based on start and end dates */
  readonly is_active?: boolean;
}

export interface EpilepsyCreateRequest {
  time_of_occurrence: string;
  duration: string;
  severity: SeverityEnum;
  state_of_consciousness: boolean;
  tremor_and_shaking: boolean;
  /** @minLength 1 */
  triggered_by?: string;
  /** @minLength 1 */
  notes?: string;
}

export interface EpilepsyDetail {
  time_of_occurrence: string;
  duration: string;
  severity: SeverityEnum;
  state_of_consciousness: boolean;
  tremor_and_shaking: boolean;
  triggered_by?: string;
  notes?: string;
  id: number;
}

export interface EpilepsyList {
  id: number;
  time_of_occurrence: string;
  duration: string;
  severity: SeverityEnum;
}

export interface Error {
  detail: string;
}

export interface Message {
  message: string;
}

export interface PaginatedDrug {
  count: number;
  /** @nullable */
  next: string | null;
  /** @nullable */
  previous: string | null;
  results: Drug[];
}

export interface PaginatedDrugDosageRetrieve {
  count: number;
  /** @nullable */
  next: string | null;
  /** @nullable */
  previous: string | null;
  results: DrugDosageRetrieve[];
}

export interface PaginatedEpilepsyList {
  count: number;
  /** @nullable */
  next: string | null;
  /** @nullable */
  previous: string | null;
  results: EpilepsyList[];
}

export interface RegisterPushNotification {
  endpoint: string;
  auth: string;
  p256dh: string;
}

export interface RegisterPushNotificationRequest {
  /** @minLength 1 */
  endpoint: string;
  /** @minLength 1 */
  auth: string;
  /** @minLength 1 */
  p256dh: string;
}

export interface ReminderTime {
  /** Unique identifier for the reminder. */
  id?: number;
  /** Time of the reminder in HH:MM format. */
  time: string;
  /** Name or label for the reminder. */
  name: string;
}

export interface ReminderTimeRequest {
  /** Unique identifier for the reminder. */
  id?: number;
  /**
   * Time of the reminder in HH:MM format.
   * @minLength 1
   */
  time: string;
  /**
   * Name or label for the reminder.
   * @minLength 1
   */
  name: string;
}

export interface RequestOTPRequest {
  /** @minLength 1 */
  phone_number: string;
}

/**
 * * `Mild` - Mild
 * `Moderate` - Moderate
 * `Severe` - Severe
 */
export type SeverityEnum = (typeof SeverityEnum)[keyof typeof SeverityEnum];

export const SeverityEnum = {
  Mild: "Mild",
  Moderate: "Moderate",
  Severe: "Severe",
} as const;

export interface Token {
  user: User;
  token: string;
}

/**
 * * `BEFORE_MEAL` - قبل از غذا
 * `AFTER_MEAL` - بعد از غذا
 * `ANYTIME` - هر زمان
 */
export type TypeOfUsageEnum = (typeof TypeOfUsageEnum)[keyof typeof TypeOfUsageEnum];

export const TypeOfUsageEnum = {
  BEFORE_MEAL: "BEFORE_MEAL",
  AFTER_MEAL: "AFTER_MEAL",
  ANYTIME: "ANYTIME",
} as const;

/**
 * * `SAT` - شنبه
 * `SUN` - یکشنبه
 * `MON` - دوشنبه
 * `TUE` - سه‌شنبه
 * `WED` - چهارشنبه
 * `THU` - پنج‌شنبه
 * `FRI` - جمعه
 */
export type UsageDaysEnum = (typeof UsageDaysEnum)[keyof typeof UsageDaysEnum];

export const UsageDaysEnum = {
  SAT: "SAT",
  SUN: "SUN",
  MON: "MON",
  TUE: "TUE",
  WED: "WED",
  THU: "THU",
  FRI: "FRI",
} as const;

export interface User {
  id: number;
  phone_number: string;
  is_active: boolean;
  last_login: string;
  date_joined: string;
}

export interface VerifyOTPRequest {
  /** @minLength 1 */
  phone_number: string;
  /**
   * @minLength 1
   * @maxLength 6
   */
  otp?: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  password?: string;
}

export type ApiDrugDosageDosemanagerDrugDosageRetrieveParams = {
  /**
   * Filter drug dosages by active status
   */
  is_active?: boolean;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Number of results to return per page.
   */
  page_size?: number;
  /**
   * Search drug dosages by drug name
   */
  search?: string;
};

/**
 * Unspecified response body
 */
export type ApiDrugDosageDosemanagerDrugDosageCreate400 = { [key: string]: unknown };

/**
 * Unspecified response body
 */
export type ApiDrugDosageDosemanagerDrugDosageRetrieve2404 = { [key: string]: unknown };

/**
 * Unspecified response body
 */
export type ApiDrugDosageDosemanagerDrugDosageUpdate400 = { [key: string]: unknown };

/**
 * Unspecified response body
 */
export type ApiDrugDosageDosemanagerDrugDosageUpdate404 = { [key: string]: unknown };

/**
 * Unspecified response body
 */
export type ApiDrugDosageDosemanagerDrugDosageDestroy404 = { [key: string]: unknown };

export type ApiDrugsDosemanagerDrugsRetrieveParams = {
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Number of results to return per page.
   */
  page_size?: number;
  /**
   * Search drugs by English or Persian name
   */
  search?: string;
};

export type ApiEpilepsyEpilepsyRetrieveParams = {
  /**
   * Filter events on a specific day (format: YYYY/MM/DD)
   */
  time_of_occurrence?: string;
  /**
   * Filter events after this date (format: YYYY/MM/DD)
   */
  time_of_occurrence_after?: string;
  /**
   * Filter events before this date (format: YYYY/MM/DD)
   */
  time_of_occurrence_before?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Logs out the current authenticated user
 */
export const apiAuthenticationAuthLogoutCreate = (options?: SecondParameter<typeof api>) => {
  return api<void>({ url: `/auth/logout/`, method: "POST" }, options);
};

/**
 * Retrieves the current authenticated user's information including ID and phone number
 */
export const apiUserAuthMeRetrieve = (options?: SecondParameter<typeof api>) => {
  return api<User>({ url: `/auth/me/`, method: "GET" }, options);
};

export const apiAuthenticationAuthRequestotpCreate = (
  requestOTPRequest: RequestOTPRequest,
  options?: SecondParameter<typeof api>,
) => {
  return api<Message>(
    { url: `/auth/requestotp/`, method: "POST", headers: { "Content-Type": "application/json" }, data: requestOTPRequest },
    options,
  );
};

export const apiAuthenticationAuthVerifyOtpCreate = (
  verifyOTPRequest: VerifyOTPRequest,
  options?: SecondParameter<typeof api>,
) => {
  return api<Token>(
    { url: `/auth/verify-otp/`, method: "POST", headers: { "Content-Type": "application/json" }, data: verifyOTPRequest },
    options,
  );
};

/**
 * This endpoint retrieves all drug dosages associated with the authenticated user with pagination support. You can filter by active status using the is_active parameter.
 * @summary Retrieve all drug dosages
 */
export const apiDrugDosageDosemanagerDrugDosageRetrieve = (
  params?: ApiDrugDosageDosemanagerDrugDosageRetrieveParams,
  options?: SecondParameter<typeof api>,
) => {
  return api<PaginatedDrugDosageRetrieve>({ url: `/dosemanager/drug-dosage/`, method: "GET", params }, options);
};

/**
 * This endpoint allows authenticated users to create a new drug dosage record. The request body must include all required fields for the DrugDosage model.
 * @summary Create a new drug dosage
 */
export const apiDrugDosageDosemanagerDrugDosageCreate = (
  drugDosageCreateUpdateRequest: DrugDosageCreateUpdateRequest,
  options?: SecondParameter<typeof api>,
) => {
  return api<DrugDosageRetrieve>(
    {
      url: `/dosemanager/drug-dosage/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: drugDosageCreateUpdateRequest,
    },
    options,
  );
};

/**
 * This endpoint retrieves a specific drug dosage by ID.
 * @summary Retrieve a specific drug dosage
 */
export const apiDrugDosageDosemanagerDrugDosageRetrieve2 = (id: number, options?: SecondParameter<typeof api>) => {
  return api<DrugDosageRetrieve>({ url: `/dosemanager/drug-dosage/${id}/`, method: "GET" }, options);
};

/**
 * This endpoint allows authenticated users to update an existing drug dosage record. The record must belong to the authenticated user.
 * @summary Update a drug dosage
 */
export const apiDrugDosageDosemanagerDrugDosageUpdate = (
  id: number,
  drugDosageCreateUpdateRequest: DrugDosageCreateUpdateRequest,
  options?: SecondParameter<typeof api>,
) => {
  return api<DrugDosageRetrieve>(
    {
      url: `/dosemanager/drug-dosage/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: drugDosageCreateUpdateRequest,
    },
    options,
  );
};

/**
 * This endpoint allows authenticated users to delete an existing drug dosage record. The record must belong to the authenticated user.
 * @summary Delete a drug dosage
 */
export const apiDrugDosageDosemanagerDrugDosageDestroy = (id: number, options?: SecondParameter<typeof api>) => {
  return api<void>({ url: `/dosemanager/drug-dosage/${id}/`, method: "DELETE" }, options);
};

/**
 * This endpoint retrieves all drugs with pagination support and search functionality.
 * @summary Retrieve all drugs
 */
export const apiDrugsDosemanagerDrugsRetrieve = (
  params?: ApiDrugsDosemanagerDrugsRetrieveParams,
  options?: SecondParameter<typeof api>,
) => {
  return api<PaginatedDrug>({ url: `/dosemanager/drugs/`, method: "GET", params }, options);
};

/**
 * Get all epilepsy events for the authenticated user
 */
export const apiEpilepsyEpilepsyRetrieve = (
  params?: ApiEpilepsyEpilepsyRetrieveParams,
  options?: SecondParameter<typeof api>,
) => {
  return api<PaginatedEpilepsyList>({ url: `/epilepsy/`, method: "GET", params }, options);
};

/**
 * Create a new epilepsy event for the authenticated user
 */
export const apiEpilepsyEpilepsyCreate = (
  epilepsyCreateRequest: EpilepsyCreateRequest,
  options?: SecondParameter<typeof api>,
) => {
  return api<EpilepsyDetail>(
    { url: `/epilepsy/`, method: "POST", headers: { "Content-Type": "application/json" }, data: epilepsyCreateRequest },
    options,
  );
};

/**
 * Get details of a specific epilepsy event for the authenticated user
 */
export const apiEpilepsyEpilepsyRetrieve2 = (id: number, options?: SecondParameter<typeof api>) => {
  return api<EpilepsyDetail>({ url: `/epilepsy/${id}/`, method: "GET" }, options);
};

/**
 * Update an epilepsy event for the authenticated user
 */
export const apiEpilepsyEpilepsyUpdate = (
  id: number,
  epilepsyCreateRequest: EpilepsyCreateRequest,
  options?: SecondParameter<typeof api>,
) => {
  return api<EpilepsyDetail>(
    { url: `/epilepsy/${id}/`, method: "PUT", headers: { "Content-Type": "application/json" }, data: epilepsyCreateRequest },
    options,
  );
};

/**
 * Delete an epilepsy event for the authenticated user
 */
export const apiEpilepsyEpilepsyDestroy = (id: number, options?: SecondParameter<typeof api>) => {
  return api<void>({ url: `/epilepsy/${id}/`, method: "DELETE" }, options);
};

/**
 * Register a new push notification token
 * @summary Register Push Notification
 */
export const apiNotificationNotificationCreate = (
  registerPushNotificationRequest: RegisterPushNotificationRequest,
  options?: SecondParameter<typeof api>,
) => {
  return api<RegisterPushNotification>(
    {
      url: `/notification/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: registerPushNotificationRequest,
    },
    options,
  );
};

export type ApiAuthenticationAuthLogoutCreateResult = NonNullable<Awaited<ReturnType<typeof apiAuthenticationAuthLogoutCreate>>>;
export type ApiUserAuthMeRetrieveResult = NonNullable<Awaited<ReturnType<typeof apiUserAuthMeRetrieve>>>;
export type ApiAuthenticationAuthRequestotpCreateResult = NonNullable<
  Awaited<ReturnType<typeof apiAuthenticationAuthRequestotpCreate>>
>;
export type ApiAuthenticationAuthVerifyOtpCreateResult = NonNullable<
  Awaited<ReturnType<typeof apiAuthenticationAuthVerifyOtpCreate>>
>;
export type ApiDrugDosageDosemanagerDrugDosageRetrieveResult = NonNullable<
  Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosageRetrieve>>
>;
export type ApiDrugDosageDosemanagerDrugDosageCreateResult = NonNullable<
  Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosageCreate>>
>;
export type ApiDrugDosageDosemanagerDrugDosageRetrieve2Result = NonNullable<
  Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosageRetrieve2>>
>;
export type ApiDrugDosageDosemanagerDrugDosageUpdateResult = NonNullable<
  Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosageUpdate>>
>;
export type ApiDrugDosageDosemanagerDrugDosageDestroyResult = NonNullable<
  Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosageDestroy>>
>;
export type ApiDrugsDosemanagerDrugsRetrieveResult = NonNullable<Awaited<ReturnType<typeof apiDrugsDosemanagerDrugsRetrieve>>>;
export type ApiEpilepsyEpilepsyRetrieveResult = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyRetrieve>>>;
export type ApiEpilepsyEpilepsyCreateResult = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyCreate>>>;
export type ApiEpilepsyEpilepsyRetrieve2Result = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyRetrieve2>>>;
export type ApiEpilepsyEpilepsyUpdateResult = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyUpdate>>>;
export type ApiEpilepsyEpilepsyDestroyResult = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyDestroy>>>;
export type ApiNotificationNotificationCreateResult = NonNullable<Awaited<ReturnType<typeof apiNotificationNotificationCreate>>>;
