/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Sarnegar API
 * Your project description
 * OpenAPI spec version: 0.1.0
 */
import { api } from './api.instance';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

export interface DrugDosage {
  readonly id: number;
  drug: number;
  dose: unknown;
  reminder_times: unknown;
  /** @maxLength 256 */
  type_of_usage: string;
  start_date: string;
  end_date?: string;
  end_by_day?: number;
  is_daily?: boolean;
  usage_days?: UsageDaysEnum[];
}

export interface EpilepsyCreate {
  time_of_occurrence: string;
  duration: string;
  severity: SeverityEnum;
  state_of_consciousness: boolean;
  tremor_and_shaking: boolean;
  triggered_by?: string;
  notes?: string;
  readonly id: number;
}

export interface EpilepsyDetail {
  time_of_occurrence: string;
  duration: string;
  severity: SeverityEnum;
  state_of_consciousness: boolean;
  tremor_and_shaking: boolean;
  triggered_by: string;
  notes: string;
  id: number;
}

export interface EpilepsyList {
  id: number;
  time_of_occurrence: string;
  duration: string;
  severity: SeverityEnum;
}

export interface Error {
  detail: string;
}

export interface Message {
  message: string;
}

export interface PaginatedEpilepsyList {
  count: number;
  /** @nullable */
  next: string | null;
  /** @nullable */
  previous: string | null;
  results: EpilepsyList[];
}

export interface RegisterPushNotification {
  endpoint: string;
  auth: string;
  p256dh: string;
}

export interface RequestOTP {
  phone_number: string;
}

/**
 * * `Mild` - Mild
* `Moderate` - Moderate
* `Severe` - Severe
 */
export type SeverityEnum = typeof SeverityEnum[keyof typeof SeverityEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeverityEnum = {
  Mild: 'Mild',
  Moderate: 'Moderate',
  Severe: 'Severe',
} as const;

export interface Token {
  user: User;
  token: string;
}

/**
 * * `SAT` - شنبه
* `SUN` - یکشنبه
* `MON` - دوشنبه
* `TUE` - سه شنبه
* `WED` - چهارشنبه
* `THU` - پنجشنبه
* `FRI` - جمعه
 */
export type UsageDaysEnum = typeof UsageDaysEnum[keyof typeof UsageDaysEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsageDaysEnum = {
  SAT: 'SAT',
  SUN: 'SUN',
  MON: 'MON',
  TUE: 'TUE',
  WED: 'WED',
  THU: 'THU',
  FRI: 'FRI',
} as const;

export interface User {
  id: number;
  phone_number: string;
  is_active: boolean;
  last_login: string;
  date_joined: string;
}

export interface VerifyOTP {
  phone_number: string;
  /** @maxLength 6 */
  otp?: string;
  /** @maxLength 128 */
  password?: string;
}

export type ApiEpilepsyEpilepsyRetrieveParams = {
/**
 * Filter events on a specific day (format: YYYY/MM/DD)
 */
time_of_occurrence?: string;
/**
 * Filter events after this date (format: YYYY/MM/DD)
 */
time_of_occurrence_after?: string;
/**
 * Filter events before this date (format: YYYY/MM/DD)
 */
time_of_occurrence_before?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Logs out the current authenticated user
 */
export const apiAuthenticationAuthLogoutCreate = (
    
 options?: SecondParameter<typeof api>,) => {
      return api<void>(
      {url: `/auth/logout/`, method: 'POST'
    },
      options);
    }
  
/**
 * Retrieves the current authenticated user's information including ID and phone number
 */
export const apiUserAuthMeRetrieve = (
    
 options?: SecondParameter<typeof api>,) => {
      return api<User>(
      {url: `/auth/me/`, method: 'GET'
    },
      options);
    }
  
export const apiAuthenticationAuthRequestotpCreate = (
    requestOTP: RequestOTP,
 options?: SecondParameter<typeof api>,) => {
      return api<Message>(
      {url: `/auth/requestotp/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestOTP
    },
      options);
    }
  
export const apiAuthenticationAuthVerifyOtpCreate = (
    verifyOTP: VerifyOTP,
 options?: SecondParameter<typeof api>,) => {
      return api<Token>(
      {url: `/auth/verify-otp/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyOTP
    },
      options);
    }
  
export const apiDrugDosageDosemanagerDrugDosagesList = (
    
 options?: SecondParameter<typeof api>,) => {
      return api<DrugDosage[]>(
      {url: `/dosemanager/drug-dosages/`, method: 'GET'
    },
      options);
    }
  
export const apiDrugDosageDosemanagerDrugDosagesCreate = (
    drugDosage: NonReadonly<DrugDosage>,
 options?: SecondParameter<typeof api>,) => {
      return api<DrugDosage>(
      {url: `/dosemanager/drug-dosages/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: drugDosage
    },
      options);
    }
  
export const apiDrugDosageDosemanagerDrugDosagesUpdate = (
    drugDosage: NonReadonly<DrugDosage>,
 options?: SecondParameter<typeof api>,) => {
      return api<DrugDosage>(
      {url: `/dosemanager/drug-dosages/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: drugDosage
    },
      options);
    }
  
export const apiDrugDosageDosemanagerDrugDosagesDestroy = (
    
 options?: SecondParameter<typeof api>,) => {
      return api<void>(
      {url: `/dosemanager/drug-dosages/`, method: 'DELETE'
    },
      options);
    }
  
export const apiDrugDosageDosemanagerDrugDosagesList2 = (
    id: number,
 options?: SecondParameter<typeof api>,) => {
      return api<DrugDosage[]>(
      {url: `/dosemanager/drug-dosages/${id}/`, method: 'GET'
    },
      options);
    }
  
export const apiDrugDosageDosemanagerDrugDosagesCreate2 = (
    id: number,
    drugDosage: NonReadonly<DrugDosage>,
 options?: SecondParameter<typeof api>,) => {
      return api<DrugDosage>(
      {url: `/dosemanager/drug-dosages/${id}/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: drugDosage
    },
      options);
    }
  
export const apiDrugDosageDosemanagerDrugDosagesUpdate2 = (
    id: number,
    drugDosage: NonReadonly<DrugDosage>,
 options?: SecondParameter<typeof api>,) => {
      return api<DrugDosage>(
      {url: `/dosemanager/drug-dosages/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: drugDosage
    },
      options);
    }
  
export const apiDrugDosageDosemanagerDrugDosagesDestroy2 = (
    id: number,
 options?: SecondParameter<typeof api>,) => {
      return api<void>(
      {url: `/dosemanager/drug-dosages/${id}/`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Get all epilepsy events for the authenticated user
 */
export const apiEpilepsyEpilepsyRetrieve = (
    params?: ApiEpilepsyEpilepsyRetrieveParams,
 options?: SecondParameter<typeof api>,) => {
      return api<PaginatedEpilepsyList>(
      {url: `/epilepsy/`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Create a new epilepsy event for the authenticated user
 */
export const apiEpilepsyEpilepsyCreate = (
    epilepsyCreate: NonReadonly<EpilepsyCreate>,
 options?: SecondParameter<typeof api>,) => {
      return api<EpilepsyDetail>(
      {url: `/epilepsy/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: epilepsyCreate
    },
      options);
    }
  
/**
 * Get details of a specific epilepsy event for the authenticated user
 */
export const apiEpilepsyEpilepsyRetrieve2 = (
    id: number,
 options?: SecondParameter<typeof api>,) => {
      return api<EpilepsyDetail>(
      {url: `/epilepsy/${id}/`, method: 'GET'
    },
      options);
    }
  
/**
 * Update an epilepsy event for the authenticated user
 */
export const apiEpilepsyEpilepsyUpdate = (
    id: number,
    epilepsyCreate: NonReadonly<EpilepsyCreate>,
 options?: SecondParameter<typeof api>,) => {
      return api<EpilepsyDetail>(
      {url: `/epilepsy/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: epilepsyCreate
    },
      options);
    }
  
/**
 * Delete an epilepsy event for the authenticated user
 */
export const apiEpilepsyEpilepsyDestroy = (
    id: number,
 options?: SecondParameter<typeof api>,) => {
      return api<void>(
      {url: `/epilepsy/${id}/`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Register a new push notification token
 * @summary Register Push Notification
 */
export const apiNotificationNotificationCreate = (
    registerPushNotification: RegisterPushNotification,
 options?: SecondParameter<typeof api>,) => {
      return api<RegisterPushNotification>(
      {url: `/notification/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerPushNotification
    },
      options);
    }
  
export type ApiAuthenticationAuthLogoutCreateResult = NonNullable<Awaited<ReturnType<typeof apiAuthenticationAuthLogoutCreate>>>
export type ApiUserAuthMeRetrieveResult = NonNullable<Awaited<ReturnType<typeof apiUserAuthMeRetrieve>>>
export type ApiAuthenticationAuthRequestotpCreateResult = NonNullable<Awaited<ReturnType<typeof apiAuthenticationAuthRequestotpCreate>>>
export type ApiAuthenticationAuthVerifyOtpCreateResult = NonNullable<Awaited<ReturnType<typeof apiAuthenticationAuthVerifyOtpCreate>>>
export type ApiDrugDosageDosemanagerDrugDosagesListResult = NonNullable<Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosagesList>>>
export type ApiDrugDosageDosemanagerDrugDosagesCreateResult = NonNullable<Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosagesCreate>>>
export type ApiDrugDosageDosemanagerDrugDosagesUpdateResult = NonNullable<Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosagesUpdate>>>
export type ApiDrugDosageDosemanagerDrugDosagesDestroyResult = NonNullable<Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosagesDestroy>>>
export type ApiDrugDosageDosemanagerDrugDosagesList2Result = NonNullable<Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosagesList2>>>
export type ApiDrugDosageDosemanagerDrugDosagesCreate2Result = NonNullable<Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosagesCreate2>>>
export type ApiDrugDosageDosemanagerDrugDosagesUpdate2Result = NonNullable<Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosagesUpdate2>>>
export type ApiDrugDosageDosemanagerDrugDosagesDestroy2Result = NonNullable<Awaited<ReturnType<typeof apiDrugDosageDosemanagerDrugDosagesDestroy2>>>
export type ApiEpilepsyEpilepsyRetrieveResult = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyRetrieve>>>
export type ApiEpilepsyEpilepsyCreateResult = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyCreate>>>
export type ApiEpilepsyEpilepsyRetrieve2Result = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyRetrieve2>>>
export type ApiEpilepsyEpilepsyUpdateResult = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyUpdate>>>
export type ApiEpilepsyEpilepsyDestroyResult = NonNullable<Awaited<ReturnType<typeof apiEpilepsyEpilepsyDestroy>>>
export type ApiNotificationNotificationCreateResult = NonNullable<Awaited<ReturnType<typeof apiNotificationNotificationCreate>>>
