import { TWheelPickerOption } from "@/common/Form/FormUtils.types";

type TCities = { [key: string]: TWheelPickerOption[] };

const cities: TCities = {
  ardbyl: [
    { value: "ardbyl", label: "اردبیل" },
    { value: "aslandvz", label: "اصلاندوز" },
    { value: "abybyglv", label: "آبی بیگلو" },
    { value: "bylhsvar", label: "بیله سوار" },
    { value: "parsabad", label: "پارس آباد" },
    { value: "tazhknd", label: "تازه کند" },
    { value: "tazhkndangvt", label: "تازه کندانگوت" },
    { value: "jafrabad", label: "جعفرآباد" },
    { value: "khlkhal", label: "خلخال" },
    { value: "rzy", label: "رضی" },
    { value: "srayn", label: "سرعین" },
    { value: "anbran", label: "عنبران" },
    { value: "fkhrabad", label: "فخرآباد" },
    { value: "klvr", label: "کلور" },
    { value: "kvrayym", label: "کوراییم" },
    { value: "grmy", label: "گرمی" },
    { value: "gyvy", label: "گیوی" },
    { value: "lahrvd", label: "لاهرود" },
    { value: "mradlv", label: "مرادلو" },
    { value: "mshgynshhr", label: "مشگین شهر" },
    { value: "nmyn", label: "نمین" },
    { value: "nyr", label: "نیر" },
    { value: "hshtjyn", label: "هشتجین" },
    { value: "hyr", label: "هیر" },
  ],
  asfhan: [
    { value: "abryshm", label: "ابریشم" },
    { value: "abvzydabad", label: "ابوزیدآباد" },
    { value: "ardstan", label: "اردستان" },
    { value: "azhyh", label: "اژیه" },
    { value: "asfhan", label: "اصفهان" },
    { value: "afvs", label: "افوس" },
    { value: "anark", label: "انارک" },
    { value: "aymanshhr", label: "ایمانشهر" },
    { value: "aranvbydgl", label: "آران وبیدگل" },
    { value: "badrvd", label: "بادرود" },
    { value: "baghbhadran", label: "باغ بهادران" },
    { value: "bafran", label: "بافران" },
    { value: "brzk", label: "برزک" },
    { value: "brfanbar", label: "برف انبار" },
    { value: "bvynvmyandsht", label: "بوئین ومیاندشت" },
    { value: "bharanshhr", label: "بهاران شهر" },
    { value: "bharstan", label: "بهارستان" },
    { value: "pyrbkran", label: "پیربکران" },
    { value: "tvdshk", label: "تودشک" },
    { value: "tyran", label: "تیران" },
    { value: "jndgh", label: "جندق" },
    { value: "jvzdan", label: "جوزدان" },
    { value: "jvshghanvkamv", label: "جوشقان وکامو" },
    { value: "chadgan", label: "چادگان" },
    { value: "chrmhyn", label: "چرمهین" },
    { value: "chmgrdan", label: "چمگردان" },
    { value: "hbybabad", label: "حبیب آباد" },
    { value: "hsnabad", label: "حسن آباد" },
    { value: "hna", label: "حنا" },
    { value: "khaldabad", label: "خالدآباد" },
    { value: "khmynyshhr", label: "خمینی شهر" },
    { value: "khvansar", label: "خوانسار" },
    { value: "khvr", label: "خور" },
    { value: "khvrasgan", label: "خوراسگان" },
    { value: "khvrzvgh", label: "خورزوق" },
    { value: "daran", label: "داران" },
    { value: "damnh", label: "دامنه" },
    { value: "drchhpyaz", label: "درچه پیاز" },
    { value: "dstgrd", label: "دستگرد" },
    { value: "dvltabad", label: "دولت آباد" },
    { value: "dhaghan", label: "دهاقان" },
    { value: "dhgh", label: "دهق" },
    { value: "dyzychh", label: "دیزیچه" },
    { value: "rzvh", label: "رزوه" },
    { value: "rzvanshhr", label: "رضوانشهر" },
    { value: "zayndhrvd", label: "زاینده رود" },
    { value: "zrynshhr", label: "زرین شهر" },
    { value: "zvarh", label: "زواره" },
    { value: "zybashhr", label: "زیباشهر" },
    { value: "sdhlnjan", label: "سده لنجان" },
    { value: "sfydshhr", label: "سفیدشهر" },
    { value: "sgzy", label: "سگزی" },
    { value: "smyrm", label: "سمیرم" },
    { value: "shapvrabad", label: "شاپورآباد" },
    { value: "shahynshhr", label: "شاهین شهر" },
    { value: "shhrza", label: "شهرضا" },
    { value: "talkhvnchh", label: "طالخونچه" },
    { value: "asgran", label: "عسگران" },
    { value: "alvychh", label: "علویچه" },
    { value: "frkhy", label: "فرخی" },
    { value: "frydvnshhr", label: "فریدونشهر" },
    { value: "flavrjan", label: "فلاورجان" },
    { value: "fvladshhr", label: "فولادشهر" },
    { value: "ghmsr", label: "قمصر" },
    { value: "ghhjavrstan", label: "قهجاورستان" },
    { value: "ghhdryjan", label: "قهدریجان" },
    { value: "kashan", label: "کاشان" },
    { value: "krkvnd", label: "کرکوند" },
    { value: "klyshadvsvdrjan", label: "کلیشادوسودرجان" },
    { value: "kmshchh", label: "کمشچه" },
    { value: "kmh", label: "کمه" },
    { value: "kvshk", label: "کوشک" },
    { value: "kvhpayh", label: "کوهپایه" },
    { value: "khryzsng", label: "کهریزسنگ" },
    { value: "grgab", label: "گرگاب" },
    { value: "gzbrkhvar", label: "گزبرخوار" },
    { value: "glpaygan", label: "گلپایگان" },
    { value: "gldsht", label: "گلدشت" },
    { value: "glshn", label: "گلشن" },
    { value: "glshhr", label: "گلشهر" },
    { value: "gvgd", label: "گوگد" },
    { value: "laybyd", label: "لای بید" },
    { value: "mbarkh", label: "مبارکه" },
    { value: "mhmdabad", label: "محمدآباد" },
    { value: "mshkat", label: "مشکات" },
    { value: "mnzryh", label: "منظریه" },
    { value: "mhabad", label: "مهاباد" },
    { value: "mymh", label: "میمه" },
    { value: "nayn", label: "نائین" },
    { value: "njfabad", label: "نجف آباد" },
    { value: "nsrabad", label: "نصرآباد" },
    { value: "ntnz", label: "نطنز" },
    { value: "nvshabad", label: "نوش آباد" },
    { value: "nyasr", label: "نیاسر" },
    { value: "nykabad", label: "نیک آباد" },
    { value: "vrznh", label: "ورزنه" },
    { value: "vrnamkhvast", label: "ورنامخواست" },
    { value: "vzvan", label: "وزوان" },
    { value: "vnk", label: "ونک" },
    { value: "hrnd", label: "هرند" },
  ],
  albrz: [
    { value: "ashthard", label: "اشتهارد" },
    { value: "asara", label: "آسارا" },
    { value: "tnkman", label: "تنکمان" },
    { value: "chharbagh", label: "چهارباغ" },
    { value: "syfabad", label: "سیف آباد" },
    { value: "shhrjdydhshtgrd", label: "شهرجدیدهشتگرد" },
    { value: "talghan", label: "طالقان" },
    { value: "krj", label: "کرج" },
    { value: "kmalshhr", label: "کمال شهر" },
    { value: "kvhsar", label: "کوهسار" },
    { value: "grmdrh", label: "گرمدره" },
    { value: "mahdsht", label: "ماهدشت" },
    { value: "mhmdshhr", label: "محمدشهر" },
    { value: "mshkyndsht", label: "مشکین دشت" },
    { value: "nzrabad", label: "نظرآباد" },
    { value: "hshtgrd", label: "هشتگرد" },
  ],
  aylam: [
    { value: "arkvaz", label: "ارکواز" },
    { value: "aylam", label: "ایلام" },
    { value: "ayvan", label: "ایوان" },
    { value: "abdanan", label: "آبدانان" },
    { value: "asmanabad", label: "آسمان آباد" },
    { value: "bdrh", label: "بدره" },
    { value: "phlh", label: "پهله" },
    { value: "tvhyd", label: "توحید" },
    { value: "chvar", label: "چوار" },
    { value: "drhshhr", label: "دره شهر" },
    { value: "dlgsha", label: "دلگشا" },
    { value: "dhlran", label: "دهلران" },
    { value: "zrnh", label: "زرنه" },
    { value: "srabbagh", label: "سراب باغ" },
    { value: "srablh", label: "سرابله" },
    { value: "salhabad", label: "صالح آباد" },
    { value: "lvmar", label: "لومار" },
    { value: "mvrmvry", label: "مورموری" },
    { value: "mvsyan", label: "موسیان" },
    { value: "mhran", label: "مهران" },
    { value: "mymh", label: "میمه" },
  ],
  azrbayjanshrghy: [
    { value: "askv", label: "اسکو" },
    { value: "ahr", label: "اهر" },
    { value: "aylkhchy", label: "ایلخچی" },
    { value: "abshahmd", label: "آبش احمد" },
    { value: "azrshhr", label: "آذرشهر" },
    { value: "aghknd", label: "آقکند" },
    { value: "basmnj", label: "باسمنج" },
    { value: "bkhshaysh", label: "بخشایش" },
    { value: "bstanabad", label: "بستان آباد" },
    { value: "bnab", label: "بناب" },
    { value: "bnabjdyd", label: "بناب جدید" },
    { value: "tbryz", label: "تبریز" },
    { value: "trk", label: "ترک" },
    { value: "trkmanchay", label: "ترکمانچای" },
    { value: "tsvj", label: "تسوج" },
    { value: "tykmhdash", label: "تیکمه داش" },
    { value: "jlfa", label: "جلفا" },
    { value: "kharvana", label: "خاروانا" },
    { value: "khamnh", label: "خامنه" },
    { value: "khrajv", label: "خراجو" },
    { value: "khsrvshhr", label: "خسروشهر" },
    { value: "khmarlv", label: "خمارلو" },
    { value: "khvajh", label: "خواجه" },
    { value: "dvzdvzan", label: "دوزدوزان" },
    { value: "zrngh", label: "زرنق" },
    { value: "znvz", label: "زنوز" },
    { value: "srab", label: "سراب" },
    { value: "srdrvd", label: "سردرود" },
    { value: "sys", label: "سیس" },
    { value: "syhrvd", label: "سیه رود" },
    { value: "shbstr", label: "شبستر" },
    { value: "shrbyan", label: "شربیان" },
    { value: "shrfkhanh", label: "شرفخانه" },
    { value: "shndabad", label: "شندآباد" },
    { value: "shhrjdydshnd", label: "شهرجدیدسهند" },
    { value: "svfyan", label: "صوفیان" },
    { value: "ajbshyr", label: "عجب شیر" },
    { value: "ghrhaghaj", label: "قره آغاج" },
    { value: "kshksray", label: "کشکسرای" },
    { value: "klvangh", label: "کلوانق" },
    { value: "klybr", label: "کلیبر" },
    { value: "kvzhknan", label: "کوزه کنان" },
    { value: "gvgan", label: "گوگان" },
    { value: "lylan", label: "لیلان" },
    { value: "mraghh", label: "مراغه" },
    { value: "mrnd", label: "مرند" },
    { value: "mlkan", label: "ملکان" },
    { value: "mmghan", label: "ممقان" },
    { value: "mhrban", label: "مهربان" },
    { value: "myanh", label: "میانه" },
    { value: "nzrkhryzy", label: "نظرکهریزی" },
    { value: "vayghan", label: "وایقان" },
    { value: "vrzghan", label: "ورزقان" },
    { value: "hadyshhr", label: "هادیشهر" },
    { value: "hrys", label: "هریس" },
    { value: "hshtrvd", label: "هشترود" },
    { value: "hvrand", label: "هوراند" },
    { value: "yamchy", label: "یامچی" },
  ],
  azrbayjanghrby: [
    { value: "arvmyh", label: "ارومیه" },
    { value: "ashnvyh", label: "اشنویه" },
    { value: "ayvavghly", label: "ایواوغلی" },
    { value: "avajygh", label: "آواجیق" },
    { value: "barvgh", label: "باروق" },
    { value: "bazrgan", label: "بازرگان" },
    { value: "bvkan", label: "بوکان" },
    { value: "pldsht", label: "پلدشت" },
    { value: "pyranshhr", label: "پیرانشهر" },
    { value: "tazhshhr", label: "تازه شهر" },
    { value: "tkab", label: "تکاب" },
    { value: "chharbrj", label: "چهاربرج" },
    { value: "khlyfan", label: "خلیفان" },
    { value: "khvy", label: "خوی" },
    { value: "dyzjdyz", label: "دیزج دیز" },
    { value: "rbt", label: "ربط" },
    { value: "srdsht", label: "سردشت" },
    { value: "srv", label: "سرو" },
    { value: "slmas", label: "سلماس" },
    { value: "sylvanh", label: "سیلوانه" },
    { value: "symynh", label: "سیمینه" },
    { value: "syhchshmh", label: "سیه چشمه" },
    { value: "shahyndzh", label: "شاهین دژ" },
    { value: "shvt", label: "شوط" },
    { value: "fyrvrgh", label: "فیرورق" },
    { value: "ghrhzyaaldyn", label: "قره ضیاءالدین" },
    { value: "ghtvr", label: "قطور" },
    { value: "ghvshchy", label: "قوشچی" },
    { value: "kshavrz", label: "کشاورز" },
    { value: "grdkshanh", label: "گردکشانه" },
    { value: "makv", label: "ماکو" },
    { value: "mhmdyar", label: "محمدیار" },
    { value: "mhmvdabad", label: "محمودآباد" },
    { value: "mhabad", label: "مهاباد" },
    { value: "myandvab", label: "میاندوآب" },
    { value: "myrabad", label: "میرآباد" },
    { value: "nalvs", label: "نالوس" },
    { value: "nghdh", label: "نقده" },
    { value: "nvshyn", label: "نوشین" },
  ],
  bvshhr: [
    { value: "amamhsn", label: "امام حسن" },
    { value: "anarstan", label: "انارستان" },
    { value: "ahrm", label: "اهرم" },
    { value: "abpkhsh", label: "آبپخش" },
    { value: "abdan", label: "آبدان" },
    { value: "brazjan", label: "برازجان" },
    { value: "brdkhvn", label: "بردخون" },
    { value: "brdstan", label: "بردستان" },
    { value: "bndrdyr", label: "بندردیر" },
    { value: "bndrdylm", label: "بندردیلم" },
    { value: "bndrryg", label: "بندرریگ" },
    { value: "bndrkngan", label: "بندرکنگان" },
    { value: "bndrgnavh", label: "بندرگناوه" },
    { value: "bnk", label: "بنک" },
    { value: "bvshhr", label: "بوشهر" },
    { value: "tngarm", label: "تنگ ارم" },
    { value: "jm", label: "جم" },
    { value: "chghadk", label: "چغادک" },
    { value: "khark", label: "خارک" },
    { value: "khvrmvj", label: "خورموج" },
    { value: "dalky", label: "دالکی" },
    { value: "dlvar", label: "دلوار" },
    { value: "ryz", label: "ریز" },
    { value: "sadabad", label: "سعدآباد" },
    { value: "syraf", label: "سیراف" },
    { value: "shbankarh", label: "شبانکاره" },
    { value: "shnbh", label: "شنبه" },
    { value: "aslvyh", label: "عسلویه" },
    { value: "kaky", label: "کاکی" },
    { value: "klmh", label: "کلمه" },
    { value: "nkhltghy", label: "نخل تقی" },
    { value: "vhdtyh", label: "وحدتیه" },
  ],
  thran: [
    { value: "thran", label: "تهران" },
    { value: "arjmnd", label: "ارجمند" },
    { value: "aslamshhr", label: "اسلامشهر" },
    { value: "andyshh", label: "اندیشه" },
    { value: "absrd", label: "آبسرد" },
    { value: "abaly", label: "آبعلی" },
    { value: "baghstan", label: "باغستان" },
    { value: "baghrshhr", label: "باقرشهر" },
    { value: "bvmhn", label: "بومهن" },
    { value: "pakdsht", label: "پاکدشت" },
    { value: "prdys", label: "پردیس" },
    { value: "pyshva", label: "پیشوا" },
    { value: "tjrysh", label: "تجریش" },
    { value: "jvadabad", label: "جوادآباد" },
    { value: "chhardangh", label: "چهاردانگه" },
    { value: "hsnabad", label: "حسن آباد" },
    { value: "dmavnd", label: "دماوند" },
    { value: "rbatkrym", label: "رباط کریم" },
    { value: "rvdhn", label: "رودهن" },
    { value: "ry", label: "ری" },
    { value: "shahdshhr", label: "شاهدشهر" },
    { value: "shryfabad", label: "شریف آباد" },
    { value: "shhryar", label: "شهریار" },
    { value: "salhabad", label: "صالح آباد" },
    { value: "sbashhr", label: "صباشهر" },
    { value: "sfadsht", label: "صفادشت" },
    { value: "frdvsyh", label: "فردوسیه" },
    { value: "frvnabad", label: "فرون آباد" },
    { value: "fshm", label: "فشم" },
    { value: "fyrvzkvh", label: "فیروزکوه" },
    { value: "ghds", label: "قدس" },
    { value: "ghrchk", label: "قرچک" },
    { value: "khryzk", label: "کهریزک" },
    { value: "kylan", label: "کیلان" },
    { value: "glstan", label: "گلستان" },
    { value: "lvasan", label: "لواسان" },
    { value: "mlard", label: "ملارد" },
    { value: "nsymshhr", label: "نسیم شهر" },
    { value: "nsyrabad", label: "نصیرآباد" },
    { value: "vhydyh", label: "وحیدیه" },
    { value: "vramyn", label: "ورامین" },
  ],
  chharmhalvbkhtyary: [
    { value: "ardl", label: "اردل" },
    { value: "alvny", label: "آلونی" },
    { value: "babahydr", label: "باباحیدر" },
    { value: "brvjn", label: "بروجن" },
    { value: "bldajy", label: "بلداجی" },
    { value: "bn", label: "بن" },
    { value: "jvnghan", label: "جونقان" },
    { value: "chlgrd", label: "چلگرد" },
    { value: "saman", label: "سامان" },
    { value: "sfyddsht", label: "سفیددشت" },
    { value: "svdjan", label: "سودجان" },
    { value: "svrshjan", label: "سورشجان" },
    { value: "shlmzar", label: "شلمزار" },
    { value: "shhrkrd", label: "شهرکرد" },
    { value: "taghank", label: "طاقانک" },
    { value: "farsan", label: "فارسان" },
    { value: "fradnbh", label: "فرادنبه" },
    { value: "frkhshhr", label: "فرخ شهر" },
    { value: "kyan", label: "کیان" },
    { value: "gndman", label: "گندمان" },
    { value: "ghrv", label: "گهرو" },
    { value: "lrdgan", label: "لردگان" },
    { value: "malkhlyfh", label: "مال خلیفه" },
    { value: "naghan", label: "ناغان" },
    { value: "nafch", label: "نافچ" },
    { value: "nghnh", label: "نقنه" },
    { value: "hfshjan", label: "هفشجان" },
  ],
  khrasanjnvby: [
    { value: "arsk", label: "ارسک" },
    { value: "asdyh", label: "اسدیه" },
    { value: "asfdn", label: "اسفدن" },
    { value: "aslamyh", label: "اسلامیه" },
    { value: "arynshhr", label: "آرین شهر" },
    { value: "aysk", label: "آیسک" },
    { value: "bshrvyh", label: "بشرویه" },
    { value: "byrjnd", label: "بیرجند" },
    { value: "hajyabad", label: "حاجی آباد" },
    { value: "khzrydshtbyaz", label: "خضری دشت بیاض" },
    { value: "khvsf", label: "خوسف" },
    { value: "zhan", label: "زهان" },
    { value: "srayan", label: "سرایان" },
    { value: "srbyshh", label: "سربیشه" },
    { value: "shghlah", label: "سه قلعه" },
    { value: "shvsf", label: "شوسف" },
    { value: "tbsmsyna", label: "طبس مسینا" },
    { value: "frdvs", label: "فردوس" },
    { value: "ghan", label: "قائن" },
    { value: "ghhstan", label: "قهستان" },
    { value: "gzyk", label: "گزیک" },
    { value: "mhmdshhr", label: "محمد شهر" },
    { value: "mvd", label: "مود" },
    { value: "nhbndan", label: "نهبندان" },
    { value: "nymblvk", label: "نیمبلوک" },
  ],
  khrasanrzvy: [
    { value: "ahmdabadsvlt", label: "احمدآبادصولت" },
    { value: "anabd", label: "انابد" },
    { value: "bajgyran", label: "باجگیران" },
    { value: "bakhrz", label: "باخرز" },
    { value: "bar", label: "بار" },
    { value: "bayg", label: "بایگ" },
    { value: "bjstan", label: "بجستان" },
    { value: "brdskn", label: "بردسکن" },
    { value: "bydkht", label: "بیدخت" },
    { value: "taybad", label: "تایباد" },
    { value: "trbtjam", label: "تربت جام" },
    { value: "trbthydryh", label: "تربت حیدریه" },
    { value: "jghtay", label: "جغتای" },
    { value: "jngl", label: "جنگل" },
    { value: "chapshlv", label: "چاپشلو" },
    { value: "chknh", label: "چکنه" },
    { value: "chnaran", label: "چناران" },
    { value: "khrv", label: "خرو" },
    { value: "khlylabad", label: "خلیل آباد" },
    { value: "khvaf", label: "خواف" },
    { value: "davrzn", label: "داورزن" },
    { value: "drgz", label: "درگز" },
    { value: "drvd", label: "درود" },
    { value: "dvltabad", label: "دولت آباد" },
    { value: "rbatsng", label: "رباط سنگ" },
    { value: "rshtkhvar", label: "رشتخوار" },
    { value: "rzvyh", label: "رضویه" },
    { value: "rvdab", label: "روداب" },
    { value: "ryvsh", label: "ریوش" },
    { value: "sbzvar", label: "سبزوار" },
    { value: "srkhs", label: "سرخس" },
    { value: "sfydsng", label: "سفیدسنگ" },
    { value: "slamy", label: "سلامی" },
    { value: "sltanabad", label: "سلطان آباد" },
    { value: "sngan", label: "سنگان" },
    { value: "shadmhr", label: "شادمهر" },
    { value: "shandyz", label: "شاندیز" },
    { value: "shshtmd", label: "ششتمد" },
    { value: "shhrabad", label: "شهرآباد" },
    { value: "shhrzv", label: "شهرزو" },
    { value: "salhabad", label: "صالح آباد" },
    { value: "trghbh", label: "طرقبه" },
    { value: "ashghabad", label: "عشق آباد" },
    { value: "frhadgrd", label: "فرهادگرد" },
    { value: "fryman", label: "فریمان" },
    { value: "fyrvzh", label: "فیروزه" },
    { value: "fyzabad", label: "فیض آباد" },
    { value: "ghasmabad", label: "قاسم آباد" },
    { value: "ghdmgah", label: "قدمگاه" },
    { value: "ghlndrabad", label: "قلندرآباد" },
    { value: "ghvchan", label: "قوچان" },
    { value: "kakhk", label: "کاخک" },
    { value: "karyz", label: "کاریز" },
    { value: "kashmr", label: "کاشمر" },
    { value: "kdkn", label: "کدکن" },
    { value: "klat", label: "کلات" },
    { value: "kndr", label: "کندر" },
    { value: "glmkan", label: "گلمکان" },
    { value: "gnabad", label: "گناباد" },
    { value: "ltfabad", label: "لطف آباد" },
    { value: "mzdavnd", label: "مزدآوند" },
    { value: "mshhd", label: "مشهد" },
    { value: "mshhdryzh", label: "مشهدریزه" },
    { value: "mlkabad", label: "ملک آباد" },
    { value: "nshtyfan", label: "نشتیفان" },
    { value: "nsrabad", label: "نصر آباد" },
    { value: "nghab", label: "نقاب" },
    { value: "nvkhndan", label: "نوخندان" },
    { value: "nyshabvr", label: "نیشابور" },
    { value: "nylshhr", label: "نیل شهر" },
    { value: "hmtabad", label: "همت آباد" },
    { value: "yvnsy", label: "یونسی" },
  ],
  khrasanshmaly: [
    { value: "asfrayn", label: "اسفراین" },
    { value: "ayvr", label: "ایور" },
    { value: "ashkhanh", label: "آشخانه" },
    { value: "bjnvrd", label: "بجنورد" },
    { value: "pyshghlah", label: "پیش قلعه" },
    { value: "tytkanlv", label: "تیتکانلو" },
    { value: "jajrm", label: "جاجرم" },
    { value: "hsargrmkhan", label: "حصارگرمخان" },
    { value: "drgh", label: "درق" },
    { value: "raz", label: "راز" },
    { value: "snkhvast", label: "سنخواست" },
    { value: "shvghan", label: "شوقان" },
    { value: "shyrvan", label: "شیروان" },
    { value: "sfyabad", label: "صفی آباد" },
    { value: "farvj", label: "فاروج" },
    { value: "ghazy", label: "قاضی" },
    { value: "grmh", label: "گرمه" },
    { value: "lvjly", label: "لوجلی" },
  ],
  khvzstan: [
    { value: "arvndknar", label: "اروندکنار" },
    { value: "alvan", label: "الوان" },
    { value: "amydyh", label: "امیدیه" },
    { value: "andymshk", label: "اندیمشک" },
    { value: "ahvaz", label: "اهواز" },
    { value: "ayzh", label: "ایذه" },
    { value: "abadan", label: "آبادان" },
    { value: "aghajary", label: "آغاجاری" },
    { value: "baghmlk", label: "باغ ملک" },
    { value: "bstan", label: "بستان" },
    { value: "bndramamkhmyny", label: "بندرامام خمینی" },
    { value: "bndrmahshhr", label: "بندرماهشهر" },
    { value: "bhbhan", label: "بهبهان" },
    { value: "trkalky", label: "ترکالکی" },
    { value: "jayzan", label: "جایزان" },
    { value: "jntmkan", label: "جنت مکان" },
    { value: "chghamysh", label: "چغامیش" },
    { value: "chmran", label: "چمران" },
    { value: "chvbdh", label: "چوئبده" },
    { value: "hr", label: "حر" },
    { value: "hsynyh", label: "حسینیه" },
    { value: "hmzh", label: "حمزه" },
    { value: "hmydyh", label: "حمیدیه" },
    { value: "khrmshhr", label: "خرمشهر" },
    { value: "darkhvyn", label: "دارخوین" },
    { value: "dzab", label: "دزآب" },
    { value: "dzfvl", label: "دزفول" },
    { value: "dhdz", label: "دهدز" },
    { value: "ramshyr", label: "رامشیر" },
    { value: "ramhrmz", label: "رامهرمز" },
    { value: "rfya", label: "رفیع" },
    { value: "zhrh", label: "زهره" },
    { value: "salnd", label: "سالند" },
    { value: "srdsht", label: "سردشت" },
    { value: "smalh", label: "سماله" },
    { value: "svsngrd", label: "سوسنگرد" },
    { value: "shadgan", label: "شادگان" },
    { value: "shavvr", label: "شاوور" },
    { value: "shraft", label: "شرافت" },
    { value: "shvsh", label: "شوش" },
    { value: "shvshtr", label: "شوشتر" },
    { value: "shyban", label: "شیبان" },
    { value: "salhshhr", label: "صالح شهر" },
    { value: "salhmshtt", label: "صالح مشطط" },
    { value: "sfyabad", label: "صفی آباد" },
    { value: "sydvn", label: "صیدون" },
    { value: "ghlahtl", label: "قلعه تل" },
    { value: "ghlahkhvajh", label: "قلعه خواجه" },
    { value: "gtvnd", label: "گتوند" },
    { value: "gvryh", label: "گوریه" },
    { value: "laly", label: "لالی" },
    { value: "msjdslyman", label: "مسجدسلیمان" },
    { value: "mshragh", label: "مشراگه" },
    { value: "mghavmt", label: "مقاومت" },
    { value: "mlasany", label: "ملاثانی" },
    { value: "myanrvd", label: "میانرود" },
    { value: "mydavd", label: "میداود" },
    { value: "mynvshhr", label: "مینوشهر" },
    { value: "vys", label: "ویس" },
    { value: "hftgl", label: "هفتگل" },
    { value: "hndyjan", label: "هندیجان" },
    { value: "hvyzh", label: "هویزه" },
  ],
  znjan: [
    { value: "abhr", label: "ابهر" },
    { value: "armghankhanh", label: "ارمغانخانه" },
    { value: "abbr", label: "آب بر" },
    { value: "chvrzgh", label: "چورزق" },
    { value: "hlb", label: "حلب" },
    { value: "khrmdrh", label: "خرمدره" },
    { value: "dndy", label: "دندی" },
    { value: "zrynabad", label: "زرین آباد" },
    { value: "zrynrvd", label: "زرین رود" },
    { value: "znjan", label: "زنجان" },
    { value: "sjas", label: "سجاس" },
    { value: "sltanyh", label: "سلطانیه" },
    { value: "shrvrd", label: "سهرورد" },
    { value: "saynghlah", label: "صائین قلعه" },
    { value: "ghydar", label: "قیدار" },
    { value: "grmab", label: "گرماب" },
    { value: "mahnshan", label: "ماه نشان" },
    { value: "hydj", label: "هیدج" },
  ],
  smnan: [
    { value: "amyryh", label: "امیریه" },
    { value: "ayvanky", label: "ایوانکی" },
    { value: "aradan", label: "آرادان" },
    { value: "bstam", label: "بسطام" },
    { value: "byarjmnd", label: "بیارجمند" },
    { value: "damghan", label: "دامغان" },
    { value: "drjzyn", label: "درجزین" },
    { value: "dybaj", label: "دیباج" },
    { value: "srkhh", label: "سرخه" },
    { value: "smnan", label: "سمنان" },
    { value: "shahrvd", label: "شاهرود" },
    { value: "shhmyrzad", label: "شهمیرزاد" },
    { value: "klathkhyj", label: "کلاته خیج" },
    { value: "grmsar", label: "گرمسار" },
    { value: "mjn", label: "مجن" },
    { value: "mhdyshhr", label: "مهدی شهر" },
    { value: "myamy", label: "میامی" },
  ],
  systanvblvchstan: [
    { value: "adymy", label: "ادیمی" },
    { value: "aspkh", label: "اسپکه" },
    { value: "ayranshhr", label: "ایرانشهر" },
    { value: "bzman", label: "بزمان" },
    { value: "bmpvr", label: "بمپور" },
    { value: "bnt", label: "بنت" },
    { value: "bnjar", label: "بنجار" },
    { value: "pyshyn", label: "پیشین" },
    { value: "jalgh", label: "جالق" },
    { value: "chahbhar", label: "چاه بهار" },
    { value: "khash", label: "خاش" },
    { value: "dvstmhmd", label: "دوست محمد" },
    { value: "rask", label: "راسک" },
    { value: "zabl", label: "زابل" },
    { value: "zably", label: "زابلی" },
    { value: "zahdan", label: "زاهدان" },
    { value: "zrabad", label: "زرآباد" },
    { value: "zhk", label: "زهک" },
    { value: "sravan", label: "سراوان" },
    { value: "srbaz", label: "سرباز" },
    { value: "svran", label: "سوران" },
    { value: "syrkan", label: "سیرکان" },
    { value: "alyakbr", label: "علی اکبر" },
    { value: "fnvj", label: "فنوج" },
    { value: "ghsrghnd", label: "قصرقند" },
    { value: "knark", label: "کنارک" },
    { value: "gsht", label: "گشت" },
    { value: "glmvrty", label: "گلمورتی" },
    { value: "mhmdan", label: "محمدان" },
    { value: "mhmdabad", label: "محمد آباد" },
    { value: "mhmdy", label: "محمدی" },
    { value: "myrjavh", label: "میرجاوه" },
    { value: "nsrtabad", label: "نصرت آباد" },
    { value: "ngvr", label: "نگور" },
    { value: "nvkabad", label: "نوک آباد" },
    { value: "nykshhr", label: "نیک شهر" },
    { value: "hydvj", label: "هیدوج" },
  ],
  fars: [
    { value: "ardkan", label: "اردکان" },
    { value: "arsnjan", label: "ارسنجان" },
    { value: "asthban", label: "استهبان" },
    { value: "asyr", label: "اسیر" },
    { value: "ashknan", label: "اشکنان" },
    { value: "afzr", label: "افزر" },
    { value: "aghlyd", label: "اقلید" },
    { value: "amamshhr", label: "امام شهر" },
    { value: "avz", label: "اوز" },
    { value: "ahl", label: "اهل" },
    { value: "ayj", label: "ایج" },
    { value: "ayzdkhvast", label: "ایزدخواست" },
    { value: "abadh", label: "آباده" },
    { value: "abadhtshk", label: "آباده طشک" },
    { value: "babanar", label: "باب انار" },
    { value: "baladh", label: "بالاده" },
    { value: "bnarvyh", label: "بنارویه" },
    { value: "bvanat", label: "بوانات" },
    { value: "bhmn", label: "بهمن" },
    { value: "byrm", label: "بیرم" },
    { value: "byza", label: "بیضا" },
    { value: "jntshhr", label: "جنت شهر" },
    { value: "jvym", label: "جویم" },
    { value: "jhrm", label: "جهرم" },
    { value: "hajyabad", label: "حاجی آباد" },
    { value: "hsamy", label: "حسامی" },
    { value: "hsnabad", label: "حسن آباد" },
    { value: "khanhznyan", label: "خانه زنیان" },
    { value: "khavran", label: "خاوران" },
    { value: "khramh", label: "خرامه" },
    { value: "khsht", label: "خشت" },
    { value: "khnj", label: "خنج" },
    { value: "khvr", label: "خور" },
    { value: "khvmhzar", label: "خومه زار" },
    { value: "darab", label: "داراب" },
    { value: "daryan", label: "داریان" },
    { value: "dbyran", label: "دبیران" },
    { value: "dzhkrd", label: "دژکرد" },
    { value: "dvbrjy", label: "دوبرجی" },
    { value: "dvzh", label: "دوزه" },
    { value: "dhrm", label: "دهرم" },
    { value: "ramjrd", label: "رامجرد" },
    { value: "rvnyz", label: "رونیز" },
    { value: "zahdshhr", label: "زاهدشهر" },
    { value: "zrghan", label: "زرقان" },
    { value: "sdh", label: "سده" },
    { value: "srvstan", label: "سروستان" },
    { value: "saadtshhr", label: "سعادت شهر" },
    { value: "svrmgh", label: "سورمق" },
    { value: "sydan", label: "سیدان" },
    { value: "shshdh", label: "ششده" },
    { value: "shhrjdydsdra", label: "شهر جدید صدرا" },
    { value: "shhrpyr", label: "شهرپیر" },
    { value: "shyraz", label: "شیراز" },
    { value: "sghad", label: "صغاد" },
    { value: "sfashhr", label: "صفاشهر" },
    { value: "alamrvdsht", label: "علامرودشت" },
    { value: "amaddh", label: "عمادده" },
    { value: "fdamy", label: "فدامی" },
    { value: "frashbnd", label: "فراشبند" },
    { value: "fsa", label: "فسا" },
    { value: "fyrvzabad", label: "فیروزآباد" },
    { value: "ghadrabad", label: "قادرآباد" },
    { value: "ghamyh", label: "قائمیه" },
    { value: "ghtbabad", label: "قطب آباد" },
    { value: "ghtrvyh", label: "قطرویه" },
    { value: "ghyr", label: "قیر" },
    { value: "karzyn", label: "کارزین" },
    { value: "kazrvn", label: "کازرون" },
    { value: "kamfyrvz", label: "کامفیروز" },
    { value: "krhay", label: "کره ای" },
    { value: "knartkhth", label: "کنارتخته" },
    { value: "kvar", label: "کوار" },
    { value: "kvhnjan", label: "کوهنجان" },
    { value: "grash", label: "گراش" },
    { value: "glhdar", label: "گله دار" },
    { value: "lar", label: "لار" },
    { value: "lamrd", label: "لامرد" },
    { value: "lpvy", label: "لپوئی" },
    { value: "ltyfy", label: "لطیفی" },
    { value: "mbarkabad", label: "مبارک آباد" },
    { value: "mrvdsht", label: "مرودشت" },
    { value: "mshkan", label: "مشکان" },
    { value: "msyry", label: "مصیری" },
    { value: "mhr", label: "مهر" },
    { value: "mymnd", label: "میمند" },
    { value: "nvbndgan", label: "نوبندگان" },
    { value: "nvjyn", label: "نوجین" },
    { value: "nvdan", label: "نودان" },
    { value: "nvrabad", label: "نورآباد" },
    { value: "nyryz", label: "نی ریز" },
    { value: "vravy", label: "وراوی" },
    { value: "hmashhr", label: "هماشهر" },
  ],
  ghzvyn: [
    { value: "ardagh", label: "ارداق" },
    { value: "asfrvryn", label: "اسفرورین" },
    { value: "aghbalyh", label: "اقبالیه" },
    { value: "alvnd", label: "الوند" },
    { value: "abgrm", label: "آبگرم" },
    { value: "abyk", label: "آبیک" },
    { value: "avj", label: "آوج" },
    { value: "bvynzhra", label: "بوئین زهرا" },
    { value: "bydstan", label: "بیدستان" },
    { value: "takstan", label: "تاکستان" },
    { value: "khakaly", label: "خاکعلی" },
    { value: "khrmdsht", label: "خرمدشت" },
    { value: "dansfhan", label: "دانسفهان" },
    { value: "razmyan", label: "رازمیان" },
    { value: "sgzabad", label: "سگزآباد" },
    { value: "syrdan", label: "سیردان" },
    { value: "shal", label: "شال" },
    { value: "shryfyh", label: "شریفیه" },
    { value: "zyaabad", label: "ضیاءآباد" },
    { value: "ghzvyn", label: "قزوین" },
    { value: "kvhyn", label: "کوهین" },
    { value: "mhmdyh", label: "محمدیه" },
    { value: "mhmvdabadnmvnh", label: "محمودآبادنمونه" },
    { value: "malmklayh", label: "معلم کلایه" },
    { value: "nrjh", label: "نرجه" },
  ],
  ghm: [
    { value: "jafryh", label: "جعفریه" },
    { value: "dstjrd", label: "دستجرد" },
    { value: "slfchgan", label: "سلفچگان" },
    { value: "ghm", label: "قم" },
    { value: "ghnvat", label: "قنوات" },
    { value: "khk", label: "کهک" },
  ],
  krdstan: [
    { value: "armrdh", label: "آرمرده" },
    { value: "babarshany", label: "بابارشانی" },
    { value: "banh", label: "بانه" },
    { value: "blbanabad", label: "بلبان آباد" },
    { value: "bvynsfly", label: "بوئین سفلی" },
    { value: "byjar", label: "بیجار" },
    { value: "chnarh", label: "چناره" },
    { value: "dzj", label: "دزج" },
    { value: "dlbran", label: "دلبران" },
    { value: "dhglan", label: "دهگلان" },
    { value: "dyvandrh", label: "دیواندره" },
    { value: "zrynh", label: "زرینه" },
    { value: "srvabad", label: "سروآباد" },
    { value: "sryshabad", label: "سریش آباد" },
    { value: "sghz", label: "سقز" },
    { value: "snndj", label: "سنندج" },
    { value: "shvyshh", label: "شویشه" },
    { value: "sahb", label: "صاحب" },
    { value: "ghrvh", label: "قروه" },
    { value: "kamyaran", label: "کامیاران" },
    { value: "kanydynar", label: "کانی دینار" },
    { value: "kanysvr", label: "کانی سور" },
    { value: "mryvan", label: "مریوان" },
    { value: "mvchsh", label: "موچش" },
    { value: "yasvknd", label: "یاسوکند" },
  ],
  krman: [
    { value: "akhtyarabad", label: "اختیارآباد" },
    { value: "arzvyh", label: "ارزوئیه" },
    { value: "amynshhr", label: "امین شهر" },
    { value: "anar", label: "انار" },
    { value: "andvhjrd", label: "اندوهجرد" },
    { value: "baghyn", label: "باغین" },
    { value: "baft", label: "بافت" },
    { value: "brdsyr", label: "بردسیر" },
    { value: "brvat", label: "بروات" },
    { value: "bznjan", label: "بزنجان" },
    { value: "bm", label: "بم" },
    { value: "bhrman", label: "بهرمان" },
    { value: "paryz", label: "پاریز" },
    { value: "jbalbarz", label: "جبالبارز" },
    { value: "jvpar", label: "جوپار" },
    { value: "jvzm", label: "جوزم" },
    { value: "jyrft", label: "جیرفت" },
    { value: "chtrvd", label: "چترود" },
    { value: "khatvnabad", label: "خاتون آباد" },
    { value: "khanvk", label: "خانوک" },
    { value: "khvrsnd", label: "خورسند" },
    { value: "drbbhsht", label: "درب بهشت" },
    { value: "dvsary", label: "دوساری" },
    { value: "dhj", label: "دهج" },
    { value: "rabr", label: "رابر" },
    { value: "ravr", label: "راور" },
    { value: "rayn", label: "راین" },
    { value: "rfsnjan", label: "رفسنجان" },
    { value: "rvdbar", label: "رودبار" },
    { value: "ryhanshhr", label: "ریحان شهر" },
    { value: "zrnd", label: "زرند" },
    { value: "zngyabad", label: "زنگی آباد" },
    { value: "zydabad", label: "زیدآباد" },
    { value: "srchshmh", label: "سرچشمه" },
    { value: "syrjan", label: "سیرجان" },
    { value: "shhdad", label: "شهداد" },
    { value: "shhrbabk", label: "شهربابک" },
    { value: "sfayh", label: "صفائیه" },
    { value: "anbrabad", label: "عنبرآباد" },
    { value: "faryab", label: "فاریاب" },
    { value: "fhrj", label: "فهرج" },
    { value: "ghlahgnj", label: "قلعه گنج" },
    { value: "kazmabad", label: "کاظم آباد" },
    { value: "krman", label: "کرمان" },
    { value: "kshkvyh", label: "کشکوئیه" },
    { value: "kvhbnan", label: "کوهبنان" },
    { value: "khnvj", label: "کهنوج" },
    { value: "kyanshhr", label: "کیانشهر" },
    { value: "glbaf", label: "گلباف" },
    { value: "glzar", label: "گلزار" },
    { value: "lalhzar", label: "لاله زار" },
    { value: "mahan", label: "ماهان" },
    { value: "mhmdabad", label: "محمد آباد" },
    { value: "mhyabad", label: "محی آباد" },
    { value: "mrdhk", label: "مردهک" },
    { value: "mnvjan", label: "منوجان" },
    { value: "njfshhr", label: "نجف شهر" },
    { value: "nrmashyr", label: "نرماشیر" },
    { value: "nzamshhr", label: "نظام شهر" },
    { value: "ngar", label: "نگار" },
    { value: "nvdzh", label: "نودژ" },
    { value: "hjdk", label: "هجدک" },
    { value: "hmashhr", label: "هماشهر" },
    { value: "yzdanshhr", label: "یزدان شهر" },
  ],
  krmanshah: [
    { value: "azglh", label: "ازگله" },
    { value: "aslamabadghrb", label: "اسلام آبادغرب" },
    { value: "bayngan", label: "باینگان" },
    { value: "bystvn", label: "بیستون" },
    { value: "pavh", label: "پاوه" },
    { value: "tazhabad", label: "تازه آباد" },
    { value: "jvanrvd", label: "جوانرود" },
    { value: "hmyl", label: "حمیل" },
    { value: "rbat", label: "رباط" },
    { value: "rvansr", label: "روانسر" },
    { value: "srplzhab", label: "سرپل ذهاب" },
    { value: "srmst", label: "سرمست" },
    { value: "str", label: "سطر" },
    { value: "snghr", label: "سنقر" },
    { value: "svmar", label: "سومار" },
    { value: "shahv", label: "شاهو" },
    { value: "shnh", label: "صحنه" },
    { value: "ghsrshyryn", label: "قصرشیرین" },
    { value: "krmanshah", label: "کرمانشاه" },
    { value: "krndghrb", label: "کرندغرب" },
    { value: "kngavr", label: "کنگاور" },
    { value: "kvzran", label: "کوزران" },
    { value: "ghvarh", label: "گهواره" },
    { value: "gylanghrb", label: "گیلانغرب" },
    { value: "myanrahan", label: "میان راهان" },
    { value: "nvdshh", label: "نودشه" },
    { value: "nvsvd", label: "نوسود" },
    { value: "hrsyn", label: "هرسین" },
    { value: "hlshy", label: "هلشی" },
  ],
  khgylvyhvbvyrahmd: [
    { value: "basht", label: "باشت" },
    { value: "patavh", label: "پاتاوه" },
    { value: "chram", label: "چرام" },
    { value: "chytab", label: "چیتاب" },
    { value: "dvgnbdan", label: "دوگنبدان" },
    { value: "dhdsht", label: "دهدشت" },
    { value: "dyshmvk", label: "دیشموک" },
    { value: "svgh", label: "سوق" },
    { value: "syskht", label: "سی سخت" },
    { value: "ghlahrysy", label: "قلعه رئیسی" },
    { value: "grabsfly", label: "گراب سفلی" },
    { value: "lndh", label: "لنده" },
    { value: "lykk", label: "لیکک" },
    { value: "madvan", label: "مادوان" },
    { value: "margvn", label: "مارگون" },
    { value: "yasvj", label: "یاسوج" },
  ],
  glstan: [
    { value: "anbaralvm", label: "انبارآلوم" },
    { value: "aynchhbrvn", label: "اینچه برون" },
    { value: "azadshhr", label: "آزادشهر" },
    { value: "aghghla", label: "آق قلا" },
    { value: "bndrgz", label: "بندرگز" },
    { value: "trkmn", label: "ترکمن" },
    { value: "jlyn", label: "جلین" },
    { value: "khanbbyn", label: "خان ببین" },
    { value: "dlnd", label: "دلند" },
    { value: "ramyan", label: "رامیان" },
    { value: "srkhnklath", label: "سرخنکلاته" },
    { value: "symynshhr", label: "سیمین شهر" },
    { value: "alyabad", label: "علی آباد" },
    { value: "fazlabad", label: "فاضل آباد" },
    { value: "krdkvy", label: "کردکوی" },
    { value: "klalh", label: "کلاله" },
    { value: "galyksh", label: "گالیکش" },
    { value: "grgan", label: "گرگان" },
    { value: "gmyshtph", label: "گمیش تپه" },
    { value: "gnbdkavvs", label: "گنبد کاووس" },
    { value: "mravhtph", label: "مراوه تپه" },
    { value: "mynvdsht", label: "مینودشت" },
    { value: "ngynshhr", label: "نگین شهر" },
    { value: "nvdhkhandvz", label: "نوده خاندوز" },
    { value: "nvkndh", label: "نوکنده" },
  ],
  gylan: [
    { value: "ahmdsrgvrab", label: "احمدسرگوراب" },
    { value: "asalm", label: "اسالم" },
    { value: "ataghvr", label: "اطاقور" },
    { value: "amlsh", label: "املش" },
    { value: "astara", label: "آستارا" },
    { value: "astanhashrfyh", label: "آستانه اشرفیه" },
    { value: "bazarjmah", label: "بازارجمعه" },
    { value: "brhsr", label: "بره سر" },
    { value: "bndranzly", label: "بندرانزلی" },
    { value: "prhsr", label: "پره سر" },
    { value: "tvtkabn", label: "توتکابن" },
    { value: "jyrndh", label: "جیرنده" },
    { value: "chabksr", label: "چابکسر" },
    { value: "chafvchmkhalh", label: "چاف وچمخاله" },
    { value: "chvbr", label: "چوبر" },
    { value: "hvygh", label: "حویق" },
    { value: "khshkbyjar", label: "خشکبیجار" },
    { value: "khmam", label: "خمام" },
    { value: "dylman", label: "دیلمان" },
    { value: "rankvh", label: "رانکوه" },
    { value: "rhymabad", label: "رحیم آباد" },
    { value: "rstmabad", label: "رستم آباد" },
    { value: "rsht", label: "رشت" },
    { value: "rzvanshhr", label: "رضوانشهر" },
    { value: "rvdbar", label: "رودبار" },
    { value: "rvdbnh", label: "رودبنه" },
    { value: "rvdsr", label: "رودسر" },
    { value: "sngr", label: "سنگر" },
    { value: "syahkl", label: "سیاهکل" },
    { value: "shft", label: "شفت" },
    { value: "shlman", label: "شلمان" },
    { value: "svmahsra", label: "صومعه سرا" },
    { value: "fvmn", label: "فومن" },
    { value: "klachay", label: "کلاچای" },
    { value: "kvchsfhan", label: "کوچصفهان" },
    { value: "kvmlh", label: "کومله" },
    { value: "kyashhr", label: "کیاشهر" },
    { value: "gvrabzrmykh", label: "گوراب زرمیخ" },
    { value: "lahyjan", label: "لاهیجان" },
    { value: "lshtnsha", label: "لشت نشاء" },
    { value: "lngrvd", label: "لنگرود" },
    { value: "lvshan", label: "لوشان" },
    { value: "lvlman", label: "لولمان" },
    { value: "lvndvyl", label: "لوندویل" },
    { value: "lysar", label: "لیسار" },
    { value: "masal", label: "ماسال" },
    { value: "masvlh", label: "ماسوله" },
    { value: "mrjghl", label: "مرجقل" },
    { value: "mnjyl", label: "منجیل" },
    { value: "vajargah", label: "واجارگاه" },
    { value: "hshtpr", label: "هشتپر" },
  ],
  lrstan: [
    { value: "azna", label: "ازنا" },
    { value: "ashtrynan", label: "اشترینان" },
    { value: "alshtr", label: "الشتر" },
    { value: "alygvdrz", label: "الیگودرز" },
    { value: "brvjrd", label: "بروجرد" },
    { value: "pldkhtr", label: "پلدختر" },
    { value: "chalanchvlan", label: "چالانچولان" },
    { value: "chghlvndy", label: "چغلوندی" },
    { value: "chghabl", label: "چقابل" },
    { value: "khrmabad", label: "خرم آباد" },
    { value: "drbgnbd", label: "درب گنبد" },
    { value: "dvrvd", label: "دورود" },
    { value: "zaghh", label: "زاغه" },
    { value: "spyddsht", label: "سپیددشت" },
    { value: "srabdvrh", label: "سراب دوره" },
    { value: "shvlabad", label: "شول آباد" },
    { value: "fyrvzabad", label: "فیروز آباد" },
    { value: "kvnany", label: "کونانی" },
    { value: "kvhdsht", label: "کوهدشت" },
    { value: "grab", label: "گراب" },
    { value: "mamvlan", label: "معمولان" },
    { value: "mmnabad", label: "مؤمن آباد" },
    { value: "nvrabad", label: "نور آباد" },
    { value: "vysyan", label: "ویسیان" },
    { value: "hftchshmh", label: "هفت چشمه" },
  ],
  mazndran: [
    { value: "amyrkla", label: "امیرکلا" },
    { value: "ayzdshhr", label: "ایزدشهر" },
    { value: "alasht", label: "آلاشت" },
    { value: "aml", label: "آمل" },
    { value: "babl", label: "بابل" },
    { value: "bablsr", label: "بابلسر" },
    { value: "bldh", label: "بلده" },
    { value: "bhshhr", label: "بهشهر" },
    { value: "bhnmyr", label: "بهنمیر" },
    { value: "plsfyd", label: "پل سفید" },
    { value: "pvl", label: "پول" },
    { value: "tnkabn", label: "تنکابن" },
    { value: "jvybar", label: "جویبار" },
    { value: "chalvs", label: "چالوس" },
    { value: "chmstan", label: "چمستان" },
    { value: "khrmabad", label: "خرم آباد" },
    { value: "khlylshhr", label: "خلیل شهر" },
    { value: "khvshrvdpy", label: "خوش رودپی" },
    { value: "dabvdsht", label: "دابودشت" },
    { value: "ramsr", label: "رامسر" },
    { value: "rstmkla", label: "رستمکلا" },
    { value: "rvyan", label: "رویان" },
    { value: "rynh", label: "رینه" },
    { value: "zrgrmhlh", label: "زرگر محله" },
    { value: "zyrab", label: "زیرآب" },
    { value: "sary", label: "ساری" },
    { value: "srkhrvd", label: "سرخرود" },
    { value: "slmanshhr", label: "سلمان شهر" },
    { value: "svrk", label: "سورک" },
    { value: "shyrgah", label: "شیرگاه" },
    { value: "shyrvd", label: "شیرود" },
    { value: "abasabad", label: "عباس آباد" },
    { value: "frydvnknar", label: "فریدونکنار" },
    { value: "frym", label: "فریم" },
    { value: "ghamshhr", label: "قائم شهر" },
    { value: "ktalmvsadatshhr", label: "کتالم وسادات شهر" },
    { value: "klarabad", label: "کلارآباد" },
    { value: "klardsht", label: "کلاردشت" },
    { value: "klhbst", label: "کله بست" },
    { value: "kvhykhyl", label: "کوهی خیل" },
    { value: "kyasr", label: "کیاسر" },
    { value: "kyakla", label: "کیاکلا" },
    { value: "gtab", label: "گتاب" },
    { value: "gznk", label: "گزنک" },
    { value: "glvgah", label: "گلوگاه" },
    { value: "mhmvdabad", label: "محمود آباد" },
    { value: "mrznabad", label: "مرزن آباد" },
    { value: "mrzykla", label: "مرزیکلا" },
    { value: "nshtarvd", label: "نشتارود" },
    { value: "nka", label: "نکا" },
    { value: "nvr", label: "نور" },
    { value: "nvshhr", label: "نوشهر" },
  ],
  mrkzy: [
    { value: "arak", label: "اراک" },
    { value: "astanh", label: "آستانه" },
    { value: "ashtyan", label: "آشتیان" },
    { value: "prndk", label: "پرندک" },
    { value: "tfrsh", label: "تفرش" },
    { value: "tvrh", label: "توره" },
    { value: "javrsyan", label: "جاورسیان" },
    { value: "khshkrvd", label: "خشکرود" },
    { value: "khmyn", label: "خمین" },
    { value: "khndab", label: "خنداب" },
    { value: "davdabad", label: "داودآباد" },
    { value: "dlyjan", label: "دلیجان" },
    { value: "razghan", label: "رازقان" },
    { value: "zavyh", label: "زاویه" },
    { value: "sarvgh", label: "ساروق" },
    { value: "savh", label: "ساوه" },
    { value: "snjan", label: "سنجان" },
    { value: "shaznd", label: "شازند" },
    { value: "shhrjdydmhajran", label: "شهرجدیدمهاجران" },
    { value: "ghrghabad", label: "غرق آباد" },
    { value: "frmhyn", label: "فرمهین" },
    { value: "ghvrchybashy", label: "قورچی باشی" },
    { value: "krhrvd", label: "کرهرود" },
    { value: "kmyjan", label: "کمیجان" },
    { value: "mmvnyh", label: "مأمونیه" },
    { value: "mhlat", label: "محلات" },
    { value: "mylajrd", label: "میلاجرد" },
    { value: "nragh", label: "نراق" },
    { value: "nvbran", label: "نوبران" },
    { value: "nymvr", label: "نیمور" },
    { value: "hndvdr", label: "هندودر" },
  ],
  hrmzgan: [
    { value: "abvmvsy", label: "ابوموسی" },
    { value: "bstk", label: "بستک" },
    { value: "bndrjask", label: "بندرجاسک" },
    { value: "bndrchark", label: "بندرچارک" },
    { value: "bndrabas", label: "بندرعباس" },
    { value: "bndrlngh", label: "بندرلنگه" },
    { value: "bykah", label: "بیکاه" },
    { value: "parsyan", label: "پارسیان" },
    { value: "tkht", label: "تخت" },
    { value: "jnah", label: "جناح" },
    { value: "hajyabad", label: "حاجی آباد" },
    { value: "khmyr", label: "خمیر" },
    { value: "drghan", label: "درگهان" },
    { value: "dhbarz", label: "دهبارز" },
    { value: "rvydr", label: "رویدر" },
    { value: "zyartaly", label: "زیارتعلی" },
    { value: "srdshtbshagrd", label: "سردشت بشاگرد" },
    { value: "srgz", label: "سرگز" },
    { value: "sndrk", label: "سندرک" },
    { value: "svza", label: "سوزا" },
    { value: "syryk", label: "سیریک" },
    { value: "farghan", label: "فارغان" },
    { value: "fyn", label: "فین" },
    { value: "ghshm", label: "قشم" },
    { value: "ghlahghazy", label: "قلعه قاضی" },
    { value: "kng", label: "کنگ" },
    { value: "kvshknar", label: "کوشکنار" },
    { value: "kysh", label: "کیش" },
    { value: "gvhran", label: "گوهران" },
    { value: "mynab", label: "میناب" },
    { value: "hrmz", label: "هرمز" },
    { value: "hshtbndy", label: "هشتبندی" },
  ],
  hmdan: [
    { value: "azndryan", label: "ازندریان" },
    { value: "asdabad", label: "اسدآباد" },
    { value: "brzvl", label: "برزول" },
    { value: "bhar", label: "بهار" },
    { value: "tvysrkan", label: "تویسرکان" },
    { value: "jvrghan", label: "جورقان" },
    { value: "jvkar", label: "جوکار" },
    { value: "dmgh", label: "دمق" },
    { value: "rzn", label: "رزن" },
    { value: "zngnh", label: "زنگنه" },
    { value: "samn", label: "سامن" },
    { value: "srkan", label: "سرکان" },
    { value: "shyrynsv", label: "شیرین سو" },
    { value: "salhabad", label: "صالح آباد" },
    { value: "famnyn", label: "فامنین" },
    { value: "frsfj", label: "فرسفج" },
    { value: "fyrvzan", label: "فیروزان" },
    { value: "ghrvhdrjzyn", label: "قروه در جزین" },
    { value: "ghhavnd", label: "قهاوند" },
    { value: "kbvdrahng", label: "کبودرآهنگ" },
    { value: "gltph", label: "گل تپه" },
    { value: "gyan", label: "گیان" },
    { value: "laljyn", label: "لالجین" },
    { value: "mryanj", label: "مریانج" },
    { value: "mlayr", label: "ملایر" },
    { value: "nhavnd", label: "نهاوند" },
    { value: "hmdan", label: "همدان" },
  ],
  yzd: [
    { value: "abrkvh", label: "ابرکوه" },
    { value: "ahmdabad", label: "احمدآباد" },
    { value: "ardkan", label: "اردکان" },
    { value: "ashkzr", label: "اشکذر" },
    { value: "bafgh", label: "بافق" },
    { value: "bfrvyh", label: "بفروئیه" },
    { value: "bhabad", label: "بهاباد" },
    { value: "tft", label: "تفت" },
    { value: "hmydya", label: "حمیدیا" },
    { value: "khzrabad", label: "خضرآباد" },
    { value: "dyhvk", label: "دیهوک" },
    { value: "zarch", label: "زارچ" },
    { value: "shahdyh", label: "شاهدیه" },
    { value: "tbs", label: "طبس" },
    { value: "ashghabad", label: "عشق آباد" },
    { value: "aghda", label: "عقدا" },
    { value: "mrvst", label: "مروست" },
    { value: "mhrdsht", label: "مهردشت" },
    { value: "mhryz", label: "مهریز" },
    { value: "mybd", label: "میبد" },
    { value: "ndvshn", label: "ندوشن" },
    { value: "nyr", label: "نیر" },
    { value: "hrat", label: "هرات" },
    { value: "yzd", label: "یزد" },
  ],
};

export const getStateCities = (state: string | null | undefined): TWheelPickerOption[] => (state ? (cities[state] ?? []) : []);
