name: Deploy React App

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: host  # Specify the environment as 'host'
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (adjust node-version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      # Step 4: Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install

      # Step 5: Add commit hash to HTML tag
      - name: Add commit hash to HTML
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Using commit hash: $COMMIT_HASH"
          # Find the index.html file (adjust path if needed)
          INDEX_FILE=$(find . -name "index.html" -not -path "*/node_modules/*" -not -path "*/dist/*" | head -n 1)
          echo "Found index.html at: $INDEX_FILE"
          # Add commit hash attribute to the <html> tag
          sed -i "s/<html/<html data-commit-hash=\"$COMMIT_HASH\"/g" $INDEX_FILE
          # Verify the change
          grep -n "<html" $INDEX_FILE

      # Step 6: Build the React app using pnpm
      - name: Build React App
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: pnpm build

      # Step 7: Verify Build Directory
      - name: Verify Build Directory
        run: |
          if [ -d "dist" ] && [ "$(ls -A dist)" ]; then
            echo "Build directory exists and is not empty."
          else
            echo "Build directory is empty or does not exist."
            exit 1
          fi

      # Step 8: Check SSH Connection
      - name: Check SSH Connection
        run: sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST }} "echo SSH connection established"

      # Step 9: Deploy Build to the Dev server if on dev branch
      - name: Deploy to Dev Server
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "dist/*"
          target: "/var/www/dev.epical/"

      # Step 10: Deploy Build to the Production server if on main branch
      - name: Deploy to Production Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "dist/"
          target: "/var/www/epical"
