name: Deploy React App

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4 # Updated to v4

      # Step 2: Setup Node.js (adjust node-version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # Use pnpm setup action
        with:
          version: 8 # Specify pnpm version (optional, defaults to latest)
          run_install: ture # We want to run install manually later


      # Step 5: Build the React app using pnpm
      - name: Build React App
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: pnpm build # Use pnpm build

      # Step 6: Deploy Build to the Dev server if on dev branch
      - name: Deploy to Dev Server
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/scp-action@v0.1.7 # Use specific version tag instead of master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "build/" # Assuming pnpm build still outputs to 'build/'
          target: "/var/www/dev.epical" # Adjust to your target directory on the dev server

      # Step 7: Deploy Build to the Production server if on main branch
      - name: Deploy to Production Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7 # Use specific version tag instead of master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "build/" # Assuming pnpm build still outputs to 'build/'
          target: "/var/www/epical" # Adjust to your target directory on the production server