name: Deploy React App

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (adjust node-version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      # Step 4: Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install

      # Step 5: Build the React app using pnpm
      - name: Build React App
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: pnpm build

      # Step 6: Verify Build Directory
      - name: Verify Build Directory
        run: |
          if [ -d "dist" ] && [ "$(ls -A dist)" ]; then
            echo "Build directory exists and is not empty."
          else
            echo "Build directory is empty or does not exist."
            exit 1
          fi

      # Step 7: Deploy Build to the Dev server if on dev branch
      - name: Deploy to Dev Server
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "dist/"
          target: "/var/www/dev.epical"

      # Step 8: Deploy Build to the Production server if on main branch
      - name: Deploy to Production Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "dist/"
          target: "/var/www/epical"